[workspace]
members = [
  "coordinator",
  "prover",
  "dev"
]

[profile.release]
opt-level = 3
lto = "thin"

[patch."https://github.com/privacy-scaling-explorations/halo2.git"]
halo2_proofs = { git = "https://github.com/pinkiebell/halo2.git", rev = "93ff44409f9ca1ea14d65449cd307c50d449af19", package = "halo2_proofs" }
