name: devops
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Ping runner workflow
        env:
          GH_OPS_PAT: ${{ secrets.GH_OPS_PAT }}
        run: |
          curl -H "authorization: token $GH_OPS_PAT" 'https://api.github.com/repos/privacy-scaling-explorations/github-ops/dispatches' -d '{"event_type":"zkevm-chain"}'
