name: Example
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  example:
    timeout-minutes: 30
    runs-on: [self-hosted, r6a.48xlarge]
    steps:
      - name: Example
        run: free -m
