name: Heavy tests
on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, labeled]

jobs:
  wakeup:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'allow-heavy-tests')
    name: Wake up self-hosted runner
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: .github/workflows/wakeup_runner.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_INSTANCE_ID: ${{ secrets.AWS_INSTANCE_ID }}

  test:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    env:
      COMPOSE_PROJECT_NAME: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
    needs: [wakeup]
    runs-on: heavy-worker
    steps:
      - name: Cleanup
        if: always()
        run: |
          sudo rm -rf ./* || true
          sudo rm -rf ./.* || true
          sudo docker system prune --all --force --volumes || true

      - uses: actions/checkout@v2

      - name: Setup
        run: cp .env.example .env

      - name: Build docker images
        run: |
          docker compose down -v --remove-orphans
          docker compose build bootnode dev

      - name: Super Circuit
        if: always()
        run: |
          docker compose run --use-aliases --no-TTY --rm --entrypoint bash dev -c 'COORDINATOR_AGGREGATE_PROOF=false COORDINATOR_CIRCUIT_NAME=super ./scripts/heavy_ci.sh'
          ./scripts/ci_commit_errors.sh super

      - name: Super Circuit aggregation
        if: always()
        run: |
          docker compose run --use-aliases --no-TTY --rm --entrypoint bash dev -c 'COORDINATOR_AGGREGATE_PROOF=true COORDINATOR_CIRCUIT_NAME=super ./scripts/heavy_ci.sh'
          ./scripts/ci_commit_errors.sh super-ag

      - name: Pi Circuit
        if: always()
        run: |
          docker compose run --use-aliases --no-TTY --rm --entrypoint bash dev -c 'COORDINATOR_AGGREGATE_PROOF=false COORDINATOR_CIRCUIT_NAME=pi ./scripts/heavy_ci.sh'
          ./scripts/ci_commit_errors.sh pi

      - name: Pi Circuit aggregation
        if: always()
        run: |
          docker compose run --use-aliases --no-TTY --rm --entrypoint bash dev -c 'COORDINATOR_AGGREGATE_PROOF=true COORDINATOR_CIRCUIT_NAME=pi ./scripts/heavy_ci.sh'
          ./scripts/ci_commit_errors.sh pi-ag

      - name: Cleanup
        if: always()
        run: |
          docker compose down -v --remove-orphans || true
          sudo rm -rf ./* || true
          sudo rm -rf ./.* || true
          sudo docker system prune --all --force --volumes || true
