name: test
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  wakeup:
    name: Wake up self-hosted runner
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: .github/workflows/wakeup_runner.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_INSTANCE_ID: ${{ secrets.AWS_INSTANCE_ID }}

  test:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    env:
      COMPOSE_PROJECT_NAME: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
    needs: [wakeup]
    runs-on: heavy-worker
    steps:
      - name: Cleanup
        if: always()
        run: |
          sudo rm -rf ./* || true
          sudo rm -rf ./.* || true
          sudo docker system prune --all --force --volumes || true

      - uses: actions/checkout@v2
        with:
          ref: ${{ (github.event.pull_request && format('refs/pull/{0}/head', github.event.pull_request.number)) || github.ref }}

      - name: Setup
        run: cp .env.example .env

      - name: Build docker images
        run: |
          docker compose down -v --remove-orphans || true
          docker compose build bootnode dev

      - name: Compile Contracts
        run: |
          docker compose run --no-TTY --rm --entrypoint bash dev -c './scripts/compile_contracts.sh'

      - name: Run coordinator tests
        run: |
          docker compose run --no-TTY --rm --entrypoint bash dev -c './scripts/load_coverage.sh && cargo test && ./scripts/get_coverage.sh'

      - name: Upload Coverage
        if: success()
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage-report.lcov
          git-branch: ${{ (github.event.pull_request && format('refs/pull/{0}/head', github.event.pull_request.number)) || github.ref }}
          git-commit: ${{ (github.event.pull_request && github.event.pull_request.head.sha) || github.sha }}

      - name: Cleanup
        if: always()
        run: |
          docker compose down -v --remove-orphans || true
          sudo rm -rf ./* || true
          sudo rm -rf ./.* || true
          sudo docker system prune --all --force --volumes || true
