name: test
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/docker-cache
          key: docker-cache-${{ runner.arch }}-${{ runner.os }}-${{ github.workflow }}-${{ github.run_id }}
          restore-keys: |
            docker-cache-${{ runner.arch }}-${{ runner.os }}-${{ github.workflow }}-

      - name: Build docker images
        run: >
          docker buildx create --name mybuilder --use &&
          docker buildx bake --load
          --set "*.cache-from=type=local,src=$RUNNER_TEMP/docker-cache"
          --set "*.cache-to=type=local,dest=$RUNNER_TEMP/docker-cache-new"
          bootnode dev

      - name: Compile Contracts
        run: |
          cp .env.example .env && docker compose run --no-TTY --rm --entrypoint bash dev -c './scripts/compile_contracts.sh && ./scripts/load_coverage.sh'

      - name: Run coordinator tests
        run: |
          docker compose run --no-TTY --rm --entrypoint bash dev -c 'cargo test'

      - name: Fix docker cache
        if: success() && github.event_name == 'push'
        run: rm -rf "$RUNNER_TEMP/docker-cache" && mv "$RUNNER_TEMP/docker-cache-new" "$RUNNER_TEMP/docker-cache"

      - name: Coverage
        run: |
          docker compose run --no-TTY --rm --entrypoint bash dev -c './scripts/get_coverage.sh'

      - name: Upload Coverage
        if: success()
        uses: coverallsapp/github-action@v1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage-report.lcov
