name: Coverage
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: [self-hosted, m6g.xlarge]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ (github.event.pull_request && format('refs/pull/{0}/head', github.event.pull_request.number)) || github.ref }}

      - name: Setup
        run: cp .env.example .env

      - name: Build docker images
        run: |
          docker compose down -v --remove-orphans || true
          docker compose build bootnode dev

      - name: Compile Contracts
        run: |
          docker compose run --no-TTY --rm --entrypoint bash dev -c './scripts/compile_contracts.sh'

      - name: Run coordinator tests
        run: |
          docker compose run --no-TTY --rm --entrypoint bash dev -c './scripts/test_coverage.sh'

      - name: Upload Coverage
        if: success()
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage-report.lcov
          git-branch: ${{ (github.event.pull_request && format('refs/pull/{0}/head', github.event.pull_request.number)) || github.ref }}
          git-commit: ${{ (github.event.pull_request && github.event.pull_request.head.sha) || github.sha }}
