name: tmp
on:
  pull_request:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: x
        run: echo '' >> prover/src/circuit_autogen.rs

      - name: Commit
        run: ./scripts/ci_autogen_commit.sh
